#!/bin/bash



# This script starts the tiling window manager depending on the operating system
# LIST:
# - detect different OS
# - Input actions like start stop reset...
# - check for updates
loadMac (){
    echo mac
    /Applications/Aerospace.app/Contents/MacOS/AeroSpace
}
loadLinux (){
    echo "Loading Linux Env"
    /mnt/c/Program\ Files/glzr.io/GlazeWM/cli/glazewm.exe start --config="/home/strozzi/configs/dotfiles/glazewm/config.yaml"
}

uname -a | grep Mac >/dev/null
if [ $? -eq 0 ]; then
    loadMac
    exit 0
fi
uname -a | grep Linux >/dev/null

if [ $? -eq 0 ]; then
    loadLinux
else
    echo "Unsupported yet..."
    exit 1
fi
