#!/bin/bash



# This script starts the tiling window manager depending on the operating system
# LIST:
# - detect different OS
# - Input actions like start stop reset...
# - check for updates
loadMac (){
    echo mac
    /Applications/Aerospace.app/Contents/MacOS/AeroSpace
}

uname -a | grep Mac >/dev/null
if [ $? -eq 0 ]; then
    loadMac
else
    echo "Unsupported yet..."
    exit 1
fi
